//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 02:32:30 AM IST 
//


package stock.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Stock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Stock">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Last" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Change" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Open" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="High" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Low" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MktCap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreviousClose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PercentageChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnnRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Earns" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="P-E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Stock", propOrder = {
    "symbol",
    "last",
    "date",
    "time",
    "change",
    "open",
    "high",
    "low",
    "volume",
    "mktCap",
    "previousClose",
    "percentageChange",
    "annRange",
    "earns",
    "pe",
    "name"
})
public class Stock {

    @XmlElement(name = "Symbol", required = true)
    protected String symbol;
    @XmlElement(name = "Last", required = true)
    protected String last;
    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "Time", required = true)
    protected String time;
    @XmlElement(name = "Change", required = true)
    protected String change;
    @XmlElement(name = "Open", required = true)
    protected String open;
    @XmlElement(name = "High", required = true)
    protected String high;
    @XmlElement(name = "Low", required = true)
    protected String low;
    @XmlElement(name = "Volume", required = true)
    protected String volume;
    @XmlElement(name = "MktCap", required = true)
    protected String mktCap;
    @XmlElement(name = "PreviousClose", required = true)
    protected String previousClose;
    @XmlElement(name = "PercentageChange", required = true)
    protected String percentageChange;
    @XmlElement(name = "AnnRange", required = true)
    protected String annRange;
    @XmlElement(name = "Earns", required = true)
    protected String earns;
    @XmlElement(name = "P-E", required = true)
    protected String pe;
    @XmlElement(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the last property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLast(String value) {
        this.last = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the change property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChange() {
        return change;
    }

    /**
     * Sets the value of the change property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChange(String value) {
        this.change = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpen(String value) {
        this.open = value;
    }

    /**
     * Gets the value of the high property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHigh() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHigh(String value) {
        this.high = value;
    }

    /**
     * Gets the value of the low property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLow() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLow(String value) {
        this.low = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the mktCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMktCap() {
        return mktCap;
    }

    /**
     * Sets the value of the mktCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMktCap(String value) {
        this.mktCap = value;
    }

    /**
     * Gets the value of the previousClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousClose() {
        return previousClose;
    }

    /**
     * Sets the value of the previousClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousClose(String value) {
        this.previousClose = value;
    }

    /**
     * Gets the value of the percentageChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageChange() {
        return percentageChange;
    }

    /**
     * Sets the value of the percentageChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageChange(String value) {
        this.percentageChange = value;
    }

    /**
     * Gets the value of the annRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnRange() {
        return annRange;
    }

    /**
     * Sets the value of the annRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnRange(String value) {
        this.annRange = value;
    }

    /**
     * Gets the value of the earns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarns() {
        return earns;
    }

    /**
     * Sets the value of the earns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarns(String value) {
        this.earns = value;
    }

    /**
     * Gets the value of the pe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPE() {
        return pe;
    }

    /**
     * Sets the value of the pe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPE(String value) {
        this.pe = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
