//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 12:17:18 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eldar.net", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cities.bind;
